drone:
  water:
    max_battery: 150
    max_payload: 5
    move_cost: 1
    drop_cost: 2
    drop_payload_cost: 1
  retardant:
    max_battery: 100
    max_payload: 1
    move_cost: 2
    drop_cost: 2
    drop_payload_cost: 1

return_to_base:
  battery_reserve: 5
